# Generated by Django 3.1.4 on 2020-12-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fira', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fira',
            name='name',
        ),
    ]
