# Generated by Django 3.1.4 on 2020-12-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fira', '0002_remove_fira_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('material', models.TextField()),
                ('vegan', models.IntegerField()),
                ('ovo', models.IntegerField()),
                ('lacto', models.IntegerField()),
                ('lactoovo', models.IntegerField()),
                ('pesco', models.IntegerField()),
                ('pollo', models.IntegerField()),
            ],
        ),
    ]
